name: GitHub Actions Build and Deploy

on:
  workflow_dispatch: # 手动触发开关（已启用）
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build
        env:
          APP_BASE_PATH: /${{ github.repository }}
        run: pnpm install --no-frozen-lockfile && pnpm run build

      # 新增：部署前清理服务器旧文件
      - name: Clean remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # 保留目录结构，仅删除内容
            sudo rm -rf /home/vitepress/dist/*
            # 保险措施：如果目录被误删则重建
            sudo mkdir -p /home/vitepress/dist

      # 优化后的部署步骤
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@7.0.2 # 更可靠的文件同步方案
        with:
          legacy_allow_rsa_hostkeys: true
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./dist/
          remote_path: /home/vitepress/dist/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.REMOTE_USERNAME }}
          remote_key:  ${{ secrets.PASSWORD }}

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.PASSWORD }}" > private.key
          chmod 600 private.key
          ssh -vvv -i private.key -p 22 ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }} "echo Connected!"

      - name: Reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: sudo nginx -s reload